#!/usr/bin/env bash
# plandb-export.sh — persist plandb state as mergeable text for git tracking.
#
# Why: binary .plandb.db in git causes merge conflicts + state loss across
# parallel worktrees. We commit text instead.
#
# Two outputs:
#   docs/plandb-state.sql       — authoritative (full state via sqlite .dump):
#                                  status, results, contexts, events, history.
#                                  Used by scripts/plandb-restore.sh for exact
#                                  recovery.
#   docs/plandb-template.yaml   — human sidecar (plandb's native export):
#                                  task graph only — titles, descriptions, deps.
#                                  NOT sufficient for state restore (drops
#                                  status / results / contexts). Reviewable in
#                                  PRs; useful as a reusable decomposition
#                                  template for similar future projects.
#
# Usage:
#   scripts/plandb-export.sh                 # default paths
#   scripts/plandb-export.sh --sql-only      # skip YAML
#   scripts/plandb-export.sh --yaml-only     # skip SQL (rarely what you want)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Honour PLANDB_DB if set — crucial when running from a worktree where
# ROOT/.plandb.db is a gitignored local copy but agents have been writing to
# the authoritative main-repo db via PLANDB_DB. Fall back to ROOT/.plandb.db.
DB="${PLANDB_DB:-${ROOT}/.plandb.db}"
SQL_OUT="${ROOT}/docs/plandb-state.sql"
YAML_OUT="${ROOT}/docs/plandb-template.yaml"
WRITE_SQL=1
WRITE_YAML=1

for arg in "$@"; do
  case "$arg" in
    --sql-only)  WRITE_YAML=0 ;;
    --yaml-only) WRITE_SQL=0 ;;
    -h|--help)
      sed -n '2,22p' "$0"
      exit 0
      ;;
    *)
      echo "plandb-export: unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

if [ ! -f "$DB" ]; then
  echo "plandb-export: no db at $DB; nothing to export." >&2
  exit 1
fi

# Safety: the authoritative db MUST contain the chief-os project (p-gtte).
# Sub-agents occasionally ran `plandb init` in their worktrees, creating a
# fresh local .plandb.db with only their sub-project — their pre-commit
# hook would then clobber docs/plandb-state.sql with a 200-line dump,
# wiping all of chief-os state. Refuse to export if p-gtte is missing.
if ! sqlite3 "$DB" "SELECT 1 FROM projects WHERE id='p-gtte' LIMIT 1;" 2>/dev/null | grep -q 1; then
  echo "plandb-export: refusing to export — db at $DB does not contain project p-gtte (chief-os)." >&2
  echo "plandb-export: if you see this in a worktree, your PLANDB_DB is pointing at a stray local db." >&2
  echo "plandb-export: fix: export PLANDB_DB=\$(git rev-parse --show-toplevel)/.plandb.db (from main clone)" >&2
  echo "plandb-export: or skip via: SKIP_PLANDB_HOOK=1 git commit ..." >&2
  exit 3
fi

if [ "$WRITE_SQL" -eq 1 ]; then
  {
    echo "-- Chief OS PlanDB state snapshot — AUTHORITATIVE"
    echo "-- Auto-generated by scripts/plandb-export.sh — do not hand-edit."
    echo "-- Source: $DB"
    echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "-- Restore: scripts/plandb-restore.sh (uses this file)."
    echo ""
    sqlite3 "$DB" .dump
  } > "$SQL_OUT"
  echo "plandb-export: wrote $SQL_OUT ($(wc -l < "$SQL_OUT" | tr -d ' ') lines, authoritative)"
fi

if [ "$WRITE_YAML" -eq 1 ]; then
  {
    echo "# Chief OS PlanDB template — human-readable sidecar."
    echo "# Auto-generated by scripts/plandb-export.sh via 'plandb export'."
    echo "# Graph shape only (titles + descriptions + deps). NOT sufficient for"
    echo "# full-state restore — status, results, and contexts are missing."
    echo "# For restore use docs/plandb-state.sql."
    echo ""
    PLANDB_DB="$DB" plandb export 2>/dev/null
  } > "$YAML_OUT"
  echo "plandb-export: wrote $YAML_OUT ($(wc -l < "$YAML_OUT" | tr -d ' ') lines, sidecar)"
fi
