export const ALL_CAPABILITY_KINDS = [
  "mem.read",
  "mem.write",
  "mem.link",
  "mem.subscribe",
  "fs.read",
  "fs.write",
  "fs.watch",
  "net.http",
  "net.ws",
  "net.oauth2",
  "llm.ai",
  "llm.harness",
  "llm.embed",
  "surface.pane",
  "ceremony.request",
  "notify.inbox",
  "agent.spawn",
  "meta.prompt",
  "meta.root_of_trust",
  "region.route",
  "clock.schedule",
  "event.emit",
  "event.subscribe",
  "ledger.read",
  "tool.invoke",
  "tool.register",
  "contact.pick",
  "file.pick",
  "share.hand_off",
  "payment.request",
  "esign.request",
  "device.mic",
  "device.camera",
  "screen.capture",
  "kbd.read_on_paste",
  "kbd.write",
  "taint.read",
] as const;

export type CapabilityKind = (typeof ALL_CAPABILITY_KINDS)[number];
