-- Chief OS PlanDB state snapshot — AUTHORITATIVE
-- Auto-generated by scripts/plandb-export.sh — do not hand-edit.
-- Source: /Users/santoshkumarradha/Documents/agentfield/code/labs/chief-os-sdk/.plandb.db
-- Generated: 2026-04-21T22:57:30Z
-- Restore: scripts/plandb-restore.sh (uses this file).

/* WARNING: Script requires that SQLITE_DBCONFIG_DEFENSIVE be disabled */
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE projects (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  description  TEXT,
  status       TEXT NOT NULL DEFAULT 'active',
  metadata     JSON,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO projects VALUES('p-wl1l','chief-os-sdk',NULL,'active',NULL,'2026-04-21 22:47:28','2026-04-21 22:47:28');
CREATE TABLE tasks (
  id                 TEXT PRIMARY KEY,
  project_id         TEXT NOT NULL REFERENCES projects(id),
  parent_task_id     TEXT REFERENCES tasks(id),
  is_composite       BOOLEAN NOT NULL DEFAULT FALSE,
  title              TEXT NOT NULL,
  description        TEXT,
  status             TEXT NOT NULL DEFAULT 'pending',
  kind               TEXT NOT NULL DEFAULT 'generic',
  priority           INTEGER NOT NULL DEFAULT 0,
  agent_id           TEXT,
  claimed_at         DATETIME,
  started_at         DATETIME,
  completed_at       DATETIME,
  result             JSON,
  error              TEXT,
  progress           INTEGER,
  progress_note      TEXT,
  max_retries        INTEGER NOT NULL DEFAULT 0,
  retry_count        INTEGER NOT NULL DEFAULT 0,
  retry_backoff      TEXT NOT NULL DEFAULT 'exponential',
  retry_delay_ms     INTEGER NOT NULL DEFAULT 1000,
  timeout_seconds    INTEGER,
  heartbeat_interval INTEGER NOT NULL DEFAULT 30,
  last_heartbeat     DATETIME,
  requires_approval  BOOLEAN NOT NULL DEFAULT FALSE,
  approval_status    TEXT,
  approved_by        TEXT,
  approval_comment   TEXT,
  pre_condition      TEXT,
  post_condition     TEXT,
  pre_hook           TEXT,
  post_hook          TEXT,
  metadata           JSON,
  created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tasks VALUES('t-4m1w','p-wl1l',NULL,1,'Read SDK contracts and workspace patterns','Read docs/16-pack-sdk.md, docs/17-os-ceremonies-and-boundaries.md, adr/0010-sdk-public-api-stability.md, CLAUDE.md, and relevant existing workspace manifests. Produce implementation constraints for the SDK, TypeScript package, prototype pack, and verification commands.','done','generic',0,'default','2026-04-21 22:48:43','2026-04-21 22:48:43','2026-04-21 22:50:13','{"summary":"Read SDK contract, OS boundary, ADR-0010, CLAUDE workflow, and workspace manifests; constraints recorded in PlanDB contexts."}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:48:43',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:08','2026-04-21 22:50:13');
INSERT INTO tasks VALUES('t-uj8f','p-wl1l',NULL,1,'Implement chief-sdk TypeScript package','Create packages/chief-sdk-ts with ESM package metadata, strict tsconfig, typed bindings mirroring Rust SDK public shapes, pane helper, useChief IPC stub hook, vitest type/runtime tests, and pane author README.','ready','generic',0,NULL,'2026-04-21 22:56:30','2026-04-21 22:56:30',NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:56:30',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:16','2026-04-21 22:56:30');
INSERT INTO tasks VALUES('t-nrn9','p-wl1l',NULL,1,'Implement chief-sdk Rust crate','Create crates/chief-sdk with Cargo.toml, public modules, traits, manifest/grant/capability/error/context/connectors APIs, curated prelude, README, and integration tests. Enforce closed CapabilityKind, non-empty usage_reason, no kernel crate re-exports, Serde round-trips, grant narrowing, and connector stubs.','done','generic',0,NULL,'2026-04-21 22:50:37','2026-04-21 22:50:37','2026-04-21 22:56:15',NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:50:37',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:16','2026-04-21 22:56:15');
INSERT INTO tasks VALUES('t-brqi','p-wl1l',NULL,0,'Update root workspace members','Edit root Cargo.toml only to add crates/chief-sdk and prototypes/hello-world-pack as workspace members while preserving existing workspace settings.','done','generic',0,'default','2026-04-21 22:50:19','2026-04-21 22:50:19','2026-04-21 22:50:30','{"file":"Cargo.toml","members_added":["crates/chief-sdk","prototypes/hello-world-pack"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:50:19',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:16','2026-04-21 22:50:30');
INSERT INTO tasks VALUES('t-7arx','p-wl1l',NULL,0,'Implement hello-world reference pack','Create prototypes/hello-world-pack with Cargo.toml depending on chief-sdk via workspace path, manifest.toml with three grants and usage_reason strings, minimal Rust pack with one Agent and one PaneDescriptor, React pane/hello.tsx, cargo tests using InMemoryConnector, and README for mock-kernel usage.','ready','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:24','2026-04-21 22:56:15');
INSERT INTO tasks VALUES('t-my3p','p-wl1l',NULL,0,'Run SDK acceptance verification','Run cargo fmt --check, cargo build/test for chief-sdk and hello-world-pack, cargo clippy --all-targets -p chief-sdk -p hello-world-pack -- -D warnings, npm run build and tests in packages/chief-sdk-ts, and search for forbidden chief-core/chief-mem imports. Fix scoped issues until acceptance criteria pass or record blockers.','pending','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:24','2026-04-21 22:48:24');
INSERT INTO tasks VALUES('t-0oxy','p-wl1l',NULL,0,'Commit SDK deliverables','After verification passes, inspect git diff/status, ensure only allowed paths changed, and create commit with message: feat(sdk): chief-sdk v0.1.0 + chief-sdk-ts + hello-world reference pack (t-w4-sdk).','pending','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:29','2026-04-21 22:48:29');
INSERT INTO tasks VALUES('t-oxd8','p-wl1l','t-4m1w',0,'Read SDK public API contract',NULL,'done','generic',0,'default','2026-04-21 22:49:04','2026-04-21 22:49:04','2026-04-21 22:49:16','{"constraints":["closed CapabilityKind","CapabilityContext-only I/O","non-empty usage_reason","no kernel imports","Rust+TS public SDK"],"read":"docs/16-pack-sdk.md"}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:49:04',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:39','2026-04-21 22:49:16');
INSERT INTO tasks VALUES('t-relc','p-wl1l','t-4m1w',0,'Read OS boundary contract',NULL,'done','generic',0,'default','2026-04-21 22:49:20','2026-04-21 22:49:20','2026-04-21 22:49:36','{"constraints":["OS-rendered ceremonies","opaque handles","no sensitive OS surfaces in pack SDK"],"read":"docs/17-os-ceremonies-and-boundaries.md"}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:49:20',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:39','2026-04-21 22:49:36');
INSERT INTO tasks VALUES('t-0cjj','p-wl1l','t-4m1w',0,'Read API stability ADR',NULL,'done','generic',0,'default','2026-04-21 22:49:41','2026-04-21 22:49:41','2026-04-21 22:49:41','{"constraints":["semver boundary","v0.1.0","major for breaking changes","ADR for new CapabilityKind","dogfood public SDK only"],"read":"adr/0010-sdk-public-api-stability.md"}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:49:41',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:39','2026-04-21 22:49:41');
INSERT INTO tasks VALUES('t-u085','p-wl1l','t-4m1w',0,'Inspect workspace build patterns',NULL,'done','generic',0,'default','2026-04-21 22:49:46','2026-04-21 22:49:46','2026-04-21 22:50:07','{"missing":"coding-style.md not found","patterns":["workspace.package inheritance","workspace.dependencies reuse","ESM TS package style"],"read":["CLAUDE.md","Cargo.toml","existing manifests"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:49:46',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:48:39','2026-04-21 22:50:07');
INSERT INTO tasks VALUES('t-qfjc','p-wl1l','t-nrn9',0,'Create chief-sdk manifest and module skeleton',NULL,'done','generic',0,'default','2026-04-21 22:51:41','2026-04-21 22:51:41','2026-04-21 22:51:41','{"created":["crates/chief-sdk/Cargo.toml","src/lib.rs","src/error.rs","src/prelude.rs"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:51:41',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:50:37','2026-04-21 22:51:41');
INSERT INTO tasks VALUES('t-iow5','p-wl1l','t-nrn9',0,'Implement capability and grant types',NULL,'done','generic',0,'default','2026-04-21 22:53:30','2026-04-21 22:53:30','2026-04-21 22:53:30','{"contracts":["closed CapabilityKind ALL list","Grant::new validates usage_reason","Grant::narrow checks subset"],"created":["src/capability.rs","src/grant.rs"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:53:30',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:50:37','2026-04-21 22:53:30');
INSERT INTO tasks VALUES('t-sz12','p-wl1l','t-nrn9',0,'Implement traits and descriptors',NULL,'done','generic',0,'default','2026-04-21 22:54:02','2026-04-21 22:54:02','2026-04-21 22:54:02','{"created":["src/agent.rs","src/pack.rs","src/tool.rs","src/ingester.rs","src/pane.rs","src/manifest.rs"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:54:02',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:50:37','2026-04-21 22:54:02');
INSERT INTO tasks VALUES('t-zbg1','p-wl1l','t-nrn9',0,'Implement context and connector facades',NULL,'done','generic',0,'default','2026-04-21 22:55:20','2026-04-21 22:55:20','2026-04-21 22:55:20','{"created":["src/connectors.rs","src/context.rs"],"features":["Memory/Event/Net/LLM facades","InMemoryConnector","NullConnector"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:55:20',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:50:37','2026-04-21 22:55:20');
INSERT INTO tasks VALUES('t-o9ea','p-wl1l','t-nrn9',0,'Add Rust SDK contract tests and README',NULL,'done','generic',0,'default','2026-04-21 22:56:15','2026-04-21 22:56:15','2026-04-21 22:56:15','{"coverage":["closed enum","usage_reason","serialization","grant narrowing","InMemoryConnector"],"created":["tests/sdk_contract.rs","README.md"]}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:56:15',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:50:37','2026-04-21 22:56:15');
INSERT INTO tasks VALUES('t-vap8','p-wl1l','t-uj8f',0,'Create TypeScript package manifest and tsconfig',NULL,'done','generic',0,'default','2026-04-21 22:57:03','2026-04-21 22:57:03','2026-04-21 22:57:03','{"created":["packages/chief-sdk-ts/package.json","packages/chief-sdk-ts/tsconfig.json"],"package":"@chief-os/sdk"}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 22:57:03',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:56:30','2026-04-21 22:57:03');
INSERT INTO tasks VALUES('t-n80i','p-wl1l','t-uj8f',0,'Implement TS SDK shapes and pane helper',NULL,'ready','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:56:30','2026-04-21 22:56:30');
INSERT INTO tasks VALUES('t-m9ot','p-wl1l','t-uj8f',0,'Implement useChief IPC stub and type tests',NULL,'ready','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:56:30','2026-04-21 22:56:30');
INSERT INTO tasks VALUES('t-18a6','p-wl1l','t-uj8f',0,'Add TS SDK README',NULL,'ready','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 22:56:30','2026-04-21 22:56:30');
CREATE TABLE dependencies (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  from_task    TEXT NOT NULL REFERENCES tasks(id),
  to_task      TEXT NOT NULL REFERENCES tasks(id),
  kind         TEXT NOT NULL DEFAULT 'blocks',
  condition    TEXT NOT NULL DEFAULT 'all',
  metadata     JSON,
  UNIQUE(from_task, to_task)
);
INSERT INTO dependencies VALUES(1,'t-4m1w','t-uj8f','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(2,'t-4m1w','t-nrn9','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(3,'t-4m1w','t-brqi','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(4,'t-nrn9','t-7arx','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(5,'t-brqi','t-7arx','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(6,'t-nrn9','t-my3p','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(7,'t-uj8f','t-my3p','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(8,'t-brqi','t-my3p','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(9,'t-7arx','t-0oxy','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(10,'t-my3p','t-0oxy','feeds_into','all',NULL);
CREATE TABLE artifacts (
  id           TEXT PRIMARY KEY,
  task_id      TEXT NOT NULL REFERENCES tasks(id),
  name         TEXT NOT NULL,
  kind         TEXT,
  content      TEXT,
  path         TEXT,
  size_bytes   INTEGER,
  mime_type    TEXT,
  metadata     JSON,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE events (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id      TEXT REFERENCES tasks(id),
  project_id   TEXT REFERENCES projects(id),
  agent_id     TEXT,
  event_type   TEXT NOT NULL,
  payload      JSON,
  timestamp    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO events VALUES(1,'t-4m1w','p-wl1l',NULL,'task_created','{"title":"Read SDK contracts and workspace patterns"}','2026-04-21 22:48:08');
INSERT INTO events VALUES(2,'t-uj8f','p-wl1l',NULL,'task_created','{"title":"Implement chief-sdk TypeScript package"}','2026-04-21 22:48:16');
INSERT INTO events VALUES(3,'t-nrn9','p-wl1l',NULL,'task_created','{"title":"Implement chief-sdk Rust crate"}','2026-04-21 22:48:16');
INSERT INTO events VALUES(4,'t-brqi','p-wl1l',NULL,'task_created','{"title":"Update root workspace members"}','2026-04-21 22:48:16');
INSERT INTO events VALUES(5,'t-7arx','p-wl1l',NULL,'task_created','{"title":"Implement hello-world reference pack"}','2026-04-21 22:48:24');
INSERT INTO events VALUES(6,'t-my3p','p-wl1l',NULL,'task_created','{"title":"Run SDK acceptance verification"}','2026-04-21 22:48:24');
INSERT INTO events VALUES(7,'t-0oxy','p-wl1l',NULL,'task_created','{"title":"Commit SDK deliverables"}','2026-04-21 22:48:29');
INSERT INTO events VALUES(8,'t-4m1w','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:48:32');
INSERT INTO events VALUES(9,'t-4m1w','p-wl1l','default','task_started',NULL,'2026-04-21 22:48:32');
INSERT INTO events VALUES(10,'t-oxd8','p-wl1l',NULL,'task_created','{"title":"Read SDK public API contract"}','2026-04-21 22:48:39');
INSERT INTO events VALUES(11,'t-relc','p-wl1l',NULL,'task_created','{"title":"Read OS boundary contract"}','2026-04-21 22:48:39');
INSERT INTO events VALUES(12,'t-0cjj','p-wl1l',NULL,'task_created','{"title":"Read API stability ADR"}','2026-04-21 22:48:39');
INSERT INTO events VALUES(13,'t-u085','p-wl1l',NULL,'task_created','{"title":"Inspect workspace build patterns"}','2026-04-21 22:48:39');
INSERT INTO events VALUES(14,'t-4m1w','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:48:43');
INSERT INTO events VALUES(15,'t-4m1w','p-wl1l','default','task_started',NULL,'2026-04-21 22:48:43');
INSERT INTO events VALUES(16,'t-oxd8','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:49:04');
INSERT INTO events VALUES(17,'t-oxd8','p-wl1l','default','task_started',NULL,'2026-04-21 22:49:04');
INSERT INTO events VALUES(18,'t-oxd8','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:49:16');
INSERT INTO events VALUES(19,'t-relc','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:49:20');
INSERT INTO events VALUES(20,'t-relc','p-wl1l','default','task_started',NULL,'2026-04-21 22:49:20');
INSERT INTO events VALUES(21,'t-relc','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:49:36');
INSERT INTO events VALUES(22,'t-0cjj','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:49:41');
INSERT INTO events VALUES(23,'t-0cjj','p-wl1l','default','task_started',NULL,'2026-04-21 22:49:41');
INSERT INTO events VALUES(24,'t-0cjj','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:49:41');
INSERT INTO events VALUES(25,'t-u085','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:49:46');
INSERT INTO events VALUES(26,'t-u085','p-wl1l','default','task_started',NULL,'2026-04-21 22:49:46');
INSERT INTO events VALUES(27,'t-u085','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:50:07');
INSERT INTO events VALUES(28,'t-4m1w','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:50:13');
INSERT INTO events VALUES(29,'t-brqi','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:50:19');
INSERT INTO events VALUES(30,'t-brqi','p-wl1l','default','task_started',NULL,'2026-04-21 22:50:19');
INSERT INTO events VALUES(31,'t-brqi','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:50:30');
INSERT INTO events VALUES(32,'t-nrn9','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:50:37');
INSERT INTO events VALUES(33,'t-nrn9','p-wl1l','default','task_started',NULL,'2026-04-21 22:50:37');
INSERT INTO events VALUES(34,'t-qfjc','p-wl1l',NULL,'task_created','{"title":"Create chief-sdk manifest and module skeleton"}','2026-04-21 22:50:37');
INSERT INTO events VALUES(35,'t-iow5','p-wl1l',NULL,'task_created','{"title":"Implement capability and grant types"}','2026-04-21 22:50:37');
INSERT INTO events VALUES(36,'t-sz12','p-wl1l',NULL,'task_created','{"title":"Implement traits and descriptors"}','2026-04-21 22:50:37');
INSERT INTO events VALUES(37,'t-zbg1','p-wl1l',NULL,'task_created','{"title":"Implement context and connector facades"}','2026-04-21 22:50:37');
INSERT INTO events VALUES(38,'t-o9ea','p-wl1l',NULL,'task_created','{"title":"Add Rust SDK contract tests and README"}','2026-04-21 22:50:37');
INSERT INTO events VALUES(39,'t-qfjc','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:51:41');
INSERT INTO events VALUES(40,'t-qfjc','p-wl1l','default','task_started',NULL,'2026-04-21 22:51:41');
INSERT INTO events VALUES(41,'t-qfjc','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:51:41');
INSERT INTO events VALUES(42,'t-iow5','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:53:30');
INSERT INTO events VALUES(43,'t-iow5','p-wl1l','default','task_started',NULL,'2026-04-21 22:53:30');
INSERT INTO events VALUES(44,'t-iow5','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:53:30');
INSERT INTO events VALUES(45,'t-sz12','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:54:02');
INSERT INTO events VALUES(46,'t-sz12','p-wl1l','default','task_started',NULL,'2026-04-21 22:54:02');
INSERT INTO events VALUES(47,'t-sz12','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:54:02');
INSERT INTO events VALUES(48,'t-zbg1','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:55:20');
INSERT INTO events VALUES(49,'t-zbg1','p-wl1l','default','task_started',NULL,'2026-04-21 22:55:20');
INSERT INTO events VALUES(50,'t-zbg1','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:55:20');
INSERT INTO events VALUES(51,'t-o9ea','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:56:15');
INSERT INTO events VALUES(52,'t-o9ea','p-wl1l','default','task_started',NULL,'2026-04-21 22:56:15');
INSERT INTO events VALUES(53,'t-o9ea','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:56:15');
INSERT INTO events VALUES(54,'t-nrn9','p-wl1l',NULL,'task_completed','{"auto_completed":true,"trigger":"t-o9ea"}','2026-04-21 22:56:15');
INSERT INTO events VALUES(55,'t-uj8f','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:56:30');
INSERT INTO events VALUES(56,'t-uj8f','p-wl1l','default','task_started',NULL,'2026-04-21 22:56:30');
INSERT INTO events VALUES(57,'t-vap8','p-wl1l',NULL,'task_created','{"title":"Create TypeScript package manifest and tsconfig"}','2026-04-21 22:56:30');
INSERT INTO events VALUES(58,'t-n80i','p-wl1l',NULL,'task_created','{"title":"Implement TS SDK shapes and pane helper"}','2026-04-21 22:56:30');
INSERT INTO events VALUES(59,'t-m9ot','p-wl1l',NULL,'task_created','{"title":"Implement useChief IPC stub and type tests"}','2026-04-21 22:56:30');
INSERT INTO events VALUES(60,'t-18a6','p-wl1l',NULL,'task_created','{"title":"Add TS SDK README"}','2026-04-21 22:56:30');
INSERT INTO events VALUES(61,'t-vap8','p-wl1l','default','task_claimed',NULL,'2026-04-21 22:57:03');
INSERT INTO events VALUES(62,'t-vap8','p-wl1l','default','task_started',NULL,'2026-04-21 22:57:03');
INSERT INTO events VALUES(63,'t-vap8','p-wl1l','default','task_completed','{"has_result":true}','2026-04-21 22:57:03');
CREATE TABLE task_tags (
  task_id  TEXT NOT NULL REFERENCES tasks(id),
  tag      TEXT NOT NULL,
  PRIMARY KEY (task_id, tag)
);
CREATE TABLE plandb_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
INSERT INTO plandb_meta VALUES('current_project','p-wl1l');
CREATE TABLE task_notes (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES tasks(id),
  agent_id TEXT,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE task_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id TEXT NOT NULL REFERENCES tasks(id),
  path TEXT NOT NULL,
  UNIQUE(task_id, path)
);
CREATE TABLE learnings (
  id           TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL REFERENCES projects(id),
  task_id      TEXT REFERENCES tasks(id),
  agent_id     TEXT,
  kind         TEXT NOT NULL DEFAULT 'discovery',
  content      TEXT NOT NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO learnings VALUES('c-zc89','p-wl1l','t-oxd8','default','constraint','SDK contract: public surface is crates/chief-sdk plus packages/chief-sdk-ts; packs must not import kernel crates; CapabilityContext is the only outside-world handle; CapabilityKind is closed and adding kinds requires ADR; every grant has typed scope and non-empty usage_reason shown at consent; v0 starts at 0.1.0; first dogfood pack should use public SDK only.','2026-04-21 22:49:16');
INSERT INTO learnings VALUES('c-ybfa','p-wl1l','t-relc','default','constraint','OS boundary contract: packs request identity/money/picker/device/time/agent-autonomy primitives, OS renders ceremonies and returns opaque handles. Sensitive surfaces like OAuth, file/contact/share pickers, ceremonies, Trust Ledger, Omnibar, status strip remain OS-exclusive; SDK should expose request/grant shapes without giving packs raw tokens, device keys, or OS surfaces.','2026-04-21 22:49:36');
INSERT INTO learnings VALUES('c-a09r','p-wl1l','t-0cjj','default','constraint','ADR-0010 stability contract: SDK is the semver boundary; version starts at 0.1.0; breaking changes require major bump plus at least one minor release deprecation window; closed CapabilityKind additions require ADR; first-party packs must dogfood public SDK only; no kernel crate imports or private entitlements.','2026-04-21 22:49:41');
INSERT INTO learnings VALUES('c-0uit','p-wl1l','t-u085','default','pattern','Workspace pattern: root Cargo workspace uses resolver=2, edition/rust-version/license/repository/publish from workspace.package, serde/tokio/async-trait/thiserror/chrono in workspace.dependencies. Existing TS prototype uses ESM, TypeScript 5.6, React 18. Commit format requires Co-Authored-By. No docs/coding-style.md file found by search; apply requested local constraints directly.','2026-04-21 22:50:06');
PRAGMA writable_schema=ON;
INSERT INTO sqlite_schema(type,name,tbl_name,rootpage,sql)VALUES('table','learnings_fts','learnings_fts',0,'CREATE VIRTUAL TABLE learnings_fts USING fts5(
  content,
  kind,
  content=''learnings'',
  content_rowid=''rowid''
)');
CREATE TABLE IF NOT EXISTS 'learnings_fts_data'(id INTEGER PRIMARY KEY, block BLOB);
INSERT INTO learnings_fts_data VALUES(1,X'04815a04');
INSERT INTO learnings_fts_data VALUES(10,X'000000000104040004010101020101030101040101');
INSERT INTO learnings_fts_data VALUES(137438953473,X'000001db023030010434040101310102350106616464696e6701022003017201022302026e6401041f0c02017401042f0601116361706162696c697479636f6e746578740102150b046b696e6401021c0204686965660104080602056c6f73656401021e02066f6e73656e740102300506747261696e74010601010204057472616374010203020572617465730104070f0107646f67666f6f640102380105656d70747901022b0204766572790102240105666972737401023701056772616e74010225010668616e646c6501021b0301730102260106696d706f7274010212020173010606120901066b65726e656c0102130204696e647301022101046d75737401021001036e6f6e01022a03017401021101046f6e6c7901041828020675747369646501021901047061636b01023905046167657301020b05017301020f02036c757301020a020575626c69630104043a0106726561736f6e01022d0306717569726573010222010573636f70650102280202646b0108020906320205686f756c6401023a0402776e01022e020574617274730102320206757266616365010205010374686501021702017301020e0204797065640102270105757361676501022c03016501023b010276300102310105776f726c6401021a0407060b06080716090a0a0b0d0a0b0c0a090a0a0b060b080b090908060a0b090906080b0b0b0a0a0a070a0b0806090a0607');
INSERT INTO learnings_fts_data VALUES(274877906945,X'000001dd06306167656e7402020c02026e64020212020775746f6e6f6d7902020d0108626f756e64617279020203010a636572656d6f6e6965730204110f02096f6e73747261696e74020601010204047461637402021b050472616374020204010664657669636502040a2a01096578636c75736976650202260304706f7365020229010466696c6502021a0106676976696e6702022e020472616e7402022b010768616e646c657302021501086964656e7469747902020701046b65797302023301066c65646765720202200203696b6502021801056d6f6e657902020801056f6175746802021902066d6e69626172020221020570617175650202140201720202340201730208020f181201057061636b730204052c020569636b657202020907017302021d020972696d69746976657302020e01037261770202300205656d61696e02022403056e64657273020210030571756573740204062603057475726e73020213010373646b0202270208656e7369746976650202160205686170657302022c0402726502021c03046f756c6402022802057461747573020222030372697002022302077572666163657302041721010474696d6502020b02056f6b656e7302023102047275737402021f0107776974686f757402022d040a070c0d101009090c0e09090b090c0d090b080a0a0b0a06090b0a060e080a0a0b0a080d0a07090a080d090a09');
INSERT INTO learnings_fts_data VALUES(412316860417,X'000001c202303003040e04020330313003020301013103020f01096164646974696f6e730302200301720304022202017403040d0c0108626f756e6461727903020a02077265616b696e670302110203756d70030215010e6361706162696c6974796b696e6403021f020668616e67657303021202056c6f73656403021e02096f6e73747261696e7403060101020405747261637403020502047261746503022d010b6465707265636174696f6e03021c02066f67666f6f64030227010c656e7469746c656d656e7473030231010566697273740302230107696d706f72747303022e02017303020701066b65726e656c03022c01056c6561737403021801056d616a6f720302140204696e6f7203021a020375737403022601026e6f03022b01036f6e6503021903026c7903022a02017203022f01057061636b73030225030372747903022402036c75730302160206726976617465030230020575626c6963030228010772656c6561736503021b0305717569726503041310010373646b030406250205656d7665720302090208746162696c697479030204040372747303020c0103746865030208010776657273696f6e03020b010677696e646f7703021d040708060e07070d0c08130b0a100a09100b110a0c060b0a0a0908070807060a08080b0a0c0b090a0d08080c');
INSERT INTO learnings_fts_data VALUES(549755813889,X'000001fe0330313804022501013204020901013504022201013604022301056170706c79040235020473796e6304021502077574686f72656404022a0102627904042b0a0105636172676f040205020568726f6e6f04021802016f040229030464696e6704022e03046d6d697404022603096e73747261696e7473040238010c646570656e64656e6369657304021b020769726563746c7904023902036f637304022d010765646974696f6e04020a0202736d040220020778697374696e6704021c010466696c6504023102056f726d61740402270303756e640402320203726f6d0402100102696e04021901076c6963656e736504020d02046f63616c04023701026d6404023001026e6f04022c01077061636b6167650402120305747465726e0408030101020208726f746f7479706504021e020675626c69736804020f010572656163740402240308706f7369746f727904020e0307717565737465640402360504697265730402280306736f6c76657204020802036f6f74040204020375737404020b01067365617263680402340303726465040213020474796c6504022f0109746869736572726f7204021702046f6b696f04021402047261697404021602017304021d02097970657363726970740402210104757365730404071a010776657273696f6e04020c0109776f726b7370616365040802060d0b04070606060a090c080a0a0609090e110c080c070c090a0808070c0907070c0d0d0b0a0d0c090b08080b08090e0909060e0a0c');
CREATE TABLE IF NOT EXISTS 'learnings_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
INSERT INTO learnings_fts_idx VALUES(1,X'',2);
INSERT INTO learnings_fts_idx VALUES(2,X'',2);
INSERT INTO learnings_fts_idx VALUES(3,X'',2);
INSERT INTO learnings_fts_idx VALUES(4,X'',2);
CREATE TABLE IF NOT EXISTS 'learnings_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
INSERT INTO learnings_fts_docsize VALUES(1,X'3d01');
INSERT INTO learnings_fts_docsize VALUES(2,X'3501');
INSERT INTO learnings_fts_docsize VALUES(3,X'3001');
INSERT INTO learnings_fts_docsize VALUES(4,X'3801');
CREATE TABLE IF NOT EXISTS 'learnings_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
INSERT INTO learnings_fts_config VALUES('version',4);
CREATE TABLE learning_tags (
  learning_id  TEXT NOT NULL REFERENCES learnings(id),
  tag          TEXT NOT NULL,
  PRIMARY KEY (learning_id, tag)
);
INSERT INTO sqlite_sequence VALUES('events',63);
INSERT INTO sqlite_sequence VALUES('dependencies',10);
CREATE VIEW task_readiness AS
SELECT
  t.id,
  t.status,
  COUNT(CASE
    WHEN d.kind IN ('blocks', 'feeds_into')
     AND upstream.status NOT IN ('done', 'done_partial')
    THEN 1
  END) AS unmet_deps,
  CASE
    WHEN t.status = 'pending'
     AND COUNT(CASE
         WHEN d.kind IN ('blocks','feeds_into')
          AND upstream.status NOT IN ('done','done_partial')
         THEN 1 END) = 0
    THEN 1 ELSE 0
  END AS promotable
FROM tasks t
LEFT JOIN dependencies d ON d.to_task = t.id
LEFT JOIN tasks upstream ON upstream.id = d.from_task
GROUP BY t.id;
CREATE INDEX idx_tasks_project_status ON tasks(project_id, status);
CREATE INDEX idx_tasks_parent ON tasks(parent_task_id);
CREATE INDEX idx_dependencies_from ON dependencies(from_task);
CREATE INDEX idx_dependencies_to ON dependencies(to_task);
CREATE INDEX idx_events_project_timestamp ON events(project_id, timestamp);
CREATE INDEX idx_task_tags_tag ON task_tags(tag);
CREATE INDEX idx_task_notes_task ON task_notes(task_id);
CREATE INDEX idx_task_files_task ON task_files(task_id);
CREATE INDEX idx_task_files_path ON task_files(path);
CREATE INDEX idx_learnings_project ON learnings(project_id);
CREATE INDEX idx_learnings_task ON learnings(task_id);
CREATE INDEX idx_learning_tags_tag ON learning_tags(tag);
PRAGMA writable_schema=OFF;
COMMIT;
