-- Chief OS PlanDB state snapshot — AUTHORITATIVE
-- Auto-generated by scripts/plandb-export.sh — do not hand-edit.
-- Source: /Users/santoshkumarradha/Documents/agentfield/code/labs/chief-os-proto-fs/.plandb.db
-- Generated: 2026-04-22T02:34:00Z
-- Restore: scripts/plandb-restore.sh (uses this file).

/* WARNING: Script requires that SQLITE_DBCONFIG_DEFENSIVE be disabled */
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE projects (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  description  TEXT,
  status       TEXT NOT NULL DEFAULT 'active',
  metadata     JSON,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO projects VALUES('p-stoc','chief-fs-prototype',NULL,'active',NULL,'2026-04-22 02:21:06','2026-04-22 02:21:06');
CREATE TABLE tasks (
  id                 TEXT PRIMARY KEY,
  project_id         TEXT NOT NULL REFERENCES projects(id),
  parent_task_id     TEXT REFERENCES tasks(id),
  is_composite       BOOLEAN NOT NULL DEFAULT FALSE,
  title              TEXT NOT NULL,
  description        TEXT,
  status             TEXT NOT NULL DEFAULT 'pending',
  kind               TEXT NOT NULL DEFAULT 'generic',
  priority           INTEGER NOT NULL DEFAULT 0,
  agent_id           TEXT,
  claimed_at         DATETIME,
  started_at         DATETIME,
  completed_at       DATETIME,
  result             JSON,
  error              TEXT,
  progress           INTEGER,
  progress_note      TEXT,
  max_retries        INTEGER NOT NULL DEFAULT 0,
  retry_count        INTEGER NOT NULL DEFAULT 0,
  retry_backoff      TEXT NOT NULL DEFAULT 'exponential',
  retry_delay_ms     INTEGER NOT NULL DEFAULT 1000,
  timeout_seconds    INTEGER,
  heartbeat_interval INTEGER NOT NULL DEFAULT 30,
  last_heartbeat     DATETIME,
  requires_approval  BOOLEAN NOT NULL DEFAULT FALSE,
  approval_status    TEXT,
  approved_by        TEXT,
  approval_comment   TEXT,
  pre_condition      TEXT,
  post_condition     TEXT,
  pre_hook           TEXT,
  post_hook          TEXT,
  metadata           JSON,
  created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tasks VALUES('t-read-contracts','p-stoc',NULL,0,'Read repo contracts','Read the repo instructions and core docs required by AGENTS.md before implementation. Produce working constraints for chief-fs: workspace style, docs requirements, axioms that affect filesystem design, and known risks/open questions. Acceptance: relevant constraints are recorded with plandb context and the task is complete before code edits.','done','generic',0,'contracts','2026-04-22 02:22:22','2026-04-22 02:22:22','2026-04-22 02:23:14','{"summary":"Read core docs plus ADR-0006 and FS research; recorded Chief FS constraints."}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:22:22',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:13','2026-04-22 02:23:14');
INSERT INTO tasks VALUES('t-inspect-workspace','p-stoc',NULL,0,'Inspect Rust workspace patterns','Inspect root Cargo.toml and existing prototype crates to match workspace/package style, Rust edition, dependency conventions, test patterns, and lint expectations. Acceptance: crate scaffold decisions are known and recorded before creating prototypes/chief-fs.','done','generic',0,'workspace','2026-04-22 02:22:22','2026-04-22 02:22:22','2026-04-22 02:23:14','{"summary":"Inspected workspace Cargo.toml and prototype crate conventions; recorded Rust workspace constraints."}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:22:22',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:19','2026-04-22 02:23:14');
INSERT INTO tasks VALUES('t-scaffold-crate','p-stoc',NULL,0,'Scaffold chief-fs crate','Create prototypes/chief-fs as a complete Rust crate, add it to root Cargo.toml workspace members, and set dependencies requested by the user including Linux-only fuser. Acceptance: Cargo metadata can see package chief-fs and the crate has src/tests/docs file placeholders ready for implementation.','done','generic',0,'codex-chief-fs','2026-04-22 02:23:21','2026-04-22 02:23:21','2026-04-22 02:23:53','{"summary":"Created prototypes/chief-fs crate, source/test/doc placeholders, and added workspace member."}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:23:21',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:26','2026-04-22 02:23:53');
INSERT INTO tasks VALUES('t-implement-cas','p-stoc',NULL,0,'Implement CAS store','Implement src/cas.rs with a blake3 content-addressed append-only blob store. Store blobs at /cas/<aa>/<bb>/<CID>, expose put/get/stat operations, validate deterministic CID behavior, and avoid overwriting existing content. Acceptance: API is testable and returns blob metadata without platform-specific dependencies.','done','generic',0,'cas-local','2026-04-22 02:24:10','2026-04-22 02:24:10','2026-04-22 02:27:03','{"summary":"Implemented blake3 CAS store with put/get/stat/path helpers and CHIEF_HOME/cas shard layout."}',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:24:10',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:32','2026-04-22 02:27:03');
INSERT INTO tasks VALUES('t-implement-aliases','p-stoc',NULL,0,'Implement alias sidecar','Implement src/aliases.rs with a rusqlite SQLite sidecar mapping logical paths to CIDs. Support set/get/delete/rename/list operations, preserve CAS blobs on alias deletes, and make rename preserve the CID while updating paths. Acceptance: deterministic, transaction-safe alias behavior with tests covering rename semantics.','done','generic',0,'default','2026-04-22 02:24:14','2026-04-22 02:24:14','2026-04-22 02:26:11',NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:24:14',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:37','2026-04-22 02:26:11');
INSERT INTO tasks VALUES('t-implement-cli','p-stoc',NULL,0,'Implement CLI','Implement src/main.rs exposing put, get, mount, and capture commands with manual argument parsing. Wire commands to CAS, alias sidecar, Linux FUSE shim, and capture daemon. Acceptance: CLI has helpful usage/errors and builds without clap on macOS and Linux.','running','generic',0,'cli-local','2026-04-22 02:27:39','2026-04-22 02:27:39',NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:27:39',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:43','2026-04-22 02:27:39');
INSERT INTO tasks VALUES('t-implement-platform','p-stoc',NULL,0,'Implement platform shims','Implement src/fuse_shim.rs as Linux-only read-only FUSE mirror using fuser behind cfg(target_os = "linux"), with a non-Linux stub returning a clear error. Implement src/capture_daemon.rs with Linux capture behavior for user-declared directories and a macOS FSEvents stub that compiles. Acceptance: cargo build works on macOS without fuser and Linux has feature-complete mount/capture entry points.','running','generic',0,'platform-worker','2026-04-22 02:27:44','2026-04-22 02:27:44',NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-22 02:27:44',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:51','2026-04-22 02:27:44');
INSERT INTO tasks VALUES('t-write-tests','p-stoc',NULL,0,'Write integration tests','Create tests/integration.rs covering CAS roundtrip, deterministic same-content CIDs, alias rename preserving CID, and capture throughput. Gate Linux-specific FUSE/capture expectations with cfg(target_os = "linux") and keep cross-platform CAS/alias tests active. Acceptance: cargo test -p chief-fs passes locally.','pending','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:21:56','2026-04-22 02:21:56');
INSERT INTO tasks VALUES('t-document-prototype','p-stoc',NULL,0,'Document chief-fs','Create prototypes/chief-fs/README.md with roughly 40 lines covering overview, usage, storage layout, FUSE/capture behavior, and limitations. Create measurements.md with performance report from local test runs and note platform constraints. Acceptance: both docs are present and accurate to implemented behavior.','pending','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:22:01','2026-04-22 02:22:01');
INSERT INTO tasks VALUES('t-verify-acceptance','p-stoc',NULL,0,'Run acceptance checks','Run cargo fmt --check, cargo build -p chief-fs, cargo test -p chief-fs, cargo clippy -p chief-fs --all-targets -- -D warnings, and cargo build --workspace on the current macOS environment. Record performance numbers and any Linux-only checks that cannot run locally. Acceptance: local checks pass or blockers are documented with exact failure context.','pending','generic',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-22 02:22:08','2026-04-22 02:22:08');
CREATE TABLE dependencies (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  from_task    TEXT NOT NULL REFERENCES tasks(id),
  to_task      TEXT NOT NULL REFERENCES tasks(id),
  kind         TEXT NOT NULL DEFAULT 'blocks',
  condition    TEXT NOT NULL DEFAULT 'all',
  metadata     JSON,
  UNIQUE(from_task, to_task)
);
INSERT INTO dependencies VALUES(1,'t-read-contracts','t-scaffold-crate','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(2,'t-inspect-workspace','t-scaffold-crate','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(3,'t-scaffold-crate','t-implement-cas','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(4,'t-scaffold-crate','t-implement-aliases','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(5,'t-implement-cas','t-implement-cli','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(6,'t-implement-aliases','t-implement-cli','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(7,'t-implement-cas','t-implement-platform','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(8,'t-implement-aliases','t-implement-platform','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(9,'t-implement-cli','t-write-tests','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(10,'t-implement-platform','t-write-tests','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(11,'t-write-tests','t-document-prototype','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(12,'t-document-prototype','t-verify-acceptance','feeds_into','all',NULL);
CREATE TABLE artifacts (
  id           TEXT PRIMARY KEY,
  task_id      TEXT NOT NULL REFERENCES tasks(id),
  name         TEXT NOT NULL,
  kind         TEXT,
  content      TEXT,
  path         TEXT,
  size_bytes   INTEGER,
  mime_type    TEXT,
  metadata     JSON,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE events (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id      TEXT REFERENCES tasks(id),
  project_id   TEXT REFERENCES projects(id),
  agent_id     TEXT,
  event_type   TEXT NOT NULL,
  payload      JSON,
  timestamp    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO events VALUES(1,'t-read-contracts','p-stoc',NULL,'task_created','{"title":"Read repo contracts"}','2026-04-22 02:21:13');
INSERT INTO events VALUES(2,'t-inspect-workspace','p-stoc',NULL,'task_created','{"title":"Inspect Rust workspace patterns"}','2026-04-22 02:21:19');
INSERT INTO events VALUES(3,'t-scaffold-crate','p-stoc',NULL,'task_created','{"title":"Scaffold chief-fs crate"}','2026-04-22 02:21:26');
INSERT INTO events VALUES(4,'t-implement-cas','p-stoc',NULL,'task_created','{"title":"Implement CAS store"}','2026-04-22 02:21:32');
INSERT INTO events VALUES(5,'t-implement-aliases','p-stoc',NULL,'task_created','{"title":"Implement alias sidecar"}','2026-04-22 02:21:37');
INSERT INTO events VALUES(6,'t-implement-cli','p-stoc',NULL,'task_created','{"title":"Implement CLI"}','2026-04-22 02:21:43');
INSERT INTO events VALUES(7,'t-implement-platform','p-stoc',NULL,'task_created','{"title":"Implement platform shims"}','2026-04-22 02:21:51');
INSERT INTO events VALUES(8,'t-write-tests','p-stoc',NULL,'task_created','{"title":"Write integration tests"}','2026-04-22 02:21:56');
INSERT INTO events VALUES(9,'t-document-prototype','p-stoc',NULL,'task_created','{"title":"Document chief-fs"}','2026-04-22 02:22:01');
INSERT INTO events VALUES(10,'t-verify-acceptance','p-stoc',NULL,'task_created','{"title":"Run acceptance checks"}','2026-04-22 02:22:08');
INSERT INTO events VALUES(11,'t-read-contracts','p-stoc','contracts','task_claimed',NULL,'2026-04-22 02:22:22');
INSERT INTO events VALUES(12,'t-read-contracts','p-stoc','contracts','task_started',NULL,'2026-04-22 02:22:22');
INSERT INTO events VALUES(13,'t-inspect-workspace','p-stoc','workspace','task_claimed',NULL,'2026-04-22 02:22:22');
INSERT INTO events VALUES(14,'t-inspect-workspace','p-stoc','workspace','task_started',NULL,'2026-04-22 02:22:22');
INSERT INTO events VALUES(15,'t-read-contracts','p-stoc','contracts','task_completed','{"has_result":true}','2026-04-22 02:23:14');
INSERT INTO events VALUES(16,'t-inspect-workspace','p-stoc','workspace','task_completed','{"has_result":true}','2026-04-22 02:23:14');
INSERT INTO events VALUES(17,'t-scaffold-crate','p-stoc','codex-chief-fs','task_claimed',NULL,'2026-04-22 02:23:21');
INSERT INTO events VALUES(18,'t-scaffold-crate','p-stoc','codex-chief-fs','task_started',NULL,'2026-04-22 02:23:21');
INSERT INTO events VALUES(19,'t-scaffold-crate','p-stoc','codex-chief-fs','task_completed','{"has_result":true}','2026-04-22 02:23:53');
INSERT INTO events VALUES(20,'t-implement-cas','p-stoc','cas-local','task_claimed',NULL,'2026-04-22 02:24:10');
INSERT INTO events VALUES(21,'t-implement-cas','p-stoc','cas-local','task_started',NULL,'2026-04-22 02:24:10');
INSERT INTO events VALUES(22,'t-implement-aliases','p-stoc','default','task_claimed',NULL,'2026-04-22 02:24:14');
INSERT INTO events VALUES(23,'t-implement-aliases','p-stoc','default','task_started',NULL,'2026-04-22 02:24:14');
INSERT INTO events VALUES(24,'t-implement-aliases','p-stoc','default','task_completed',NULL,'2026-04-22 02:26:11');
INSERT INTO events VALUES(25,'t-implement-cas','p-stoc','cas-local','task_completed','{"has_result":true}','2026-04-22 02:27:03');
INSERT INTO events VALUES(26,'t-implement-cli','p-stoc','cli-local','task_claimed',NULL,'2026-04-22 02:27:39');
INSERT INTO events VALUES(27,'t-implement-cli','p-stoc','cli-local','task_started',NULL,'2026-04-22 02:27:39');
INSERT INTO events VALUES(28,'t-implement-platform','p-stoc','platform-worker','task_claimed',NULL,'2026-04-22 02:27:44');
INSERT INTO events VALUES(29,'t-implement-platform','p-stoc','platform-worker','task_started',NULL,'2026-04-22 02:27:44');
CREATE TABLE task_tags (
  task_id  TEXT NOT NULL REFERENCES tasks(id),
  tag      TEXT NOT NULL,
  PRIMARY KEY (task_id, tag)
);
CREATE TABLE plandb_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
INSERT INTO plandb_meta VALUES('current_project','p-stoc');
CREATE TABLE task_notes (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES tasks(id),
  agent_id TEXT,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE task_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id TEXT NOT NULL REFERENCES tasks(id),
  path TEXT NOT NULL,
  UNIQUE(task_id, path)
);
CREATE TABLE learnings (
  id           TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL REFERENCES projects(id),
  task_id      TEXT REFERENCES tasks(id),
  agent_id     TEXT,
  kind         TEXT NOT NULL DEFAULT 'discovery',
  content      TEXT NOT NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO learnings VALUES('c-trxg','p-stoc','t-read-contracts','contracts','discovery','Chief FS constraints: accepted ADR-0006 defines BLAKE3 CAS plus FUSE human-folder shim; CIDs must survive rename/move; deletes/tombstones preserve CAS blobs; capture daemon hashes writes, updates alias/index, and eventually emits provenance events. Prototype should stay local-first and boring below L2.','2026-04-22 02:23:03');
INSERT INTO learnings VALUES('c-pglj','p-stoc','t-inspect-workspace','workspace','discovery','Rust workspace patterns: root workspace resolver=2, edition 2021, rust-version 1.75; prototypes are workspace members with package-local Cargo.toml, src/lib.rs for libraries, tests/ for integration. Workspace deps include blake3, tokio, anyhow, serde, rusqlite bundled, chrono, tempfile; uuid is used by chief-inference but not yet workspace-level.','2026-04-22 02:23:08');
INSERT INTO learnings VALUES('c-ojmb','p-stoc','t-implement-aliases','default','blocker','Implemented SQLite-backed alias store in prototypes/chief-fs/src/aliases.rs. cargo test -p chief-fs could not complete in this environment because dependency resolution needs crates.io access and offline mode reports missing fuser for chief-fs.','2026-04-22 02:26:11');
INSERT INTO learnings VALUES('c-jz55','p-stoc','t-implement-cas','cas-local','discovery','CAS implementation uses BLAKE3 lowercase hex CIDs and stores blobs under CHIEF_HOME/cas/aa/bb/cid. put_bytes writes via same-directory temp file + hard link publish, so existing blobs are not overwritten and duplicate content resolves to the existing blob.','2026-04-22 02:26:55');
INSERT INTO learnings VALUES('c-7x5j','p-stoc',NULL,'default','discovery','chief-fs prototype will keep alias store at chief_home/aliases.sqlite and CAS at chief_home/cas, with capture_paths doing a recursive one-shot ingest of declared directories for v0 while fanotify/FSEvents remain platform-specific shims.','2026-04-22 02:28:27');
PRAGMA writable_schema=ON;
INSERT INTO sqlite_schema(type,name,tbl_name,rootpage,sql)VALUES('table','learnings_fts','learnings_fts',0,'CREATE VIRTUAL TABLE learnings_fts USING fts5(
  content,
  kind,
  content=''learnings'',
  content_rowid=''rowid''
)');
CREATE TABLE IF NOT EXISTS 'learnings_fts_data'(id INTEGER PRIMARY KEY, block BLOB);
INSERT INTO learnings_fts_data VALUES(1,X'05815905');
INSERT INTO learnings_fts_data VALUES(10,X'000000000105050005010101020101030101040101050101');
INSERT INTO learnings_fts_data VALUES(137438953473,X'000001bc053030303036010207010861636365707465640102050202647201020602046c69617301021f02026e640104210c010562656c6f7701022d02056c616b653301020903036f627301021902056f72696e6701022c01076361707475726501021a03017301040a100204686965660102020203696473010210020a6f6e73747261696e747301020401066461656d6f6e01021b02066566696e657301020803056c6574657301021502086973636f7665727901060101020105656d697473010223020576656e7473010225060575616c6c790102220105666972737401022a02056f6c64657201020e020173010203020375736501020c010668617368657301021c0204756d616e01020d0105696e64657801022001026c3201022e02046f63616c01022901046d6f766501021402037573740102110104706c757301020b02077265736572766501021703076f746f74797065010226040776656e616e6365010224010672656e616d6501021301047368696d01020f03046f756c6401022702037461790102280206757276697665010212010a746f6d6273746f6e657301021601077570646174657301021e010677726974657301021d04090d0709080a0a080a0c0709080f0b0b0a0f0a0a0a0a0a06080b090a07090908090c0c0c0b0909080b0f0c');
INSERT INTO learnings_fts_data VALUES(274877906945,X'000001c902303102020d010132020208020330323102020a0102373502020e0106616e79686f77020225020272650202100106626c616b65330202230206756e646c656402022803017402023102017902022e0105636172676f02021602046869656602022f0304726f6e6f02022901046465707302022102086973636f766572790206010102010765646974696f6e0202090103666f7202041b050107696e636c7564650202220307666572656e63650202300309746567726174696f6e02021f02017302022c01056c6576656c02023502026962020219040672617269657302021c02046f63616c02021501076d656d6265727302021201036e6f7402023201077061636b6167650202140306747465726e730202040209726f746f747970657302020f01087265736f6c76657202020702036f6f7402020502017302021a02077573716c6974650202270401740204020b0105736572646502022602027263020218010874656d7066696c6502022a030373747302021d02046f6b696f02022403026d6c02021701047573656402022d020375696402022b010776657273696f6e02020c01047769746802021302086f726b7370616365020a03050d1116010379657402023304060608070b070b0b06060a0909090f0c090c0c0e060a070b090c080c0b0e0d08060c070a070d08090709080c0911');
INSERT INTO learnings_fts_data VALUES(412316860417,X'00000161073061636365737303021f02046c6961730302050602657303020c02026e6403022001066261636b6564030204020665636175736503021902066c6f636b657203060101020105636172676f03020e0204686965660306090a1802076f6d706c6574650302150303756c640302130205726174657303021d010a646570656e64656e637903021a010b656e7669726f6e6d656e740302180103666f7203022602017303060a0a18020475736572030225010b696d706c656d656e74656403020202016e0304071102016f03021e01076d697373696e6703022402036f646503022201056e6565647303021c02026f7403021401076f66666c696e650302210101700302100209726f746f747970657303020801077265706f7274730302230308736f6c7574696f6e03021b02017303020d010673716c6974650302030202726303020b0204746f726503020601047465737403020f0203686973030217040b0907070b0b0d0a0b0c080a0f100808091007060c080a070c060e0c0d060b070909');
INSERT INTO learnings_fts_data VALUES(549755813889,X'000001780330616104021002026e640404091d020272650402210102626204021102056c616b653304020503026f6204022b05017304040b1702047974657304021401036361730404020f02046869656604020d0202696404021204017304020802066f6e74656e7404022601096469726563746f7279040218030773636f766572790406010102020875706c696361746504022501086578697374696e6704041f0d010466696c6504021a01046861726404021b0202657804020702036f6d6504020e010e696d706c656d656e746174696f6e04020301046c696e6b04021c02086f7765726361736504020601036e6f74040222010b6f7665727772697474656e04022301077075626c69736804021d03017404021301087265736f6c766573040227010473616d6504021702016f04021e0205746f72657304020a010474656d700402190202686504022902016f0402280105756e64657204020c02037365730402040103766961040216010677726974657304021504070807070a070709090907060b0e0e0d0e0909070813090d08100c060d09060a0907060a0808');
INSERT INTO learnings_fts_data VALUES(687194767361,X'0000015402306105021802046c6961730502070602657305020c02026e6405020e0201740504090901076361707475726505021503017305040f060204686965660506020a0901086465636c6172656405021e020a69726563746f7269657305021f030773636f76657279050601010202046f696e67050217010866616e6f7469667905022302026f7205022002017305020303066576656e74730502240104686f6d6505040b090106696e6765737405021c01046b65657005020601026f6605021d02026e6505021a0105706174687305021602076c6174666f726d0502260208726f746f74797065050204010972656375727369766505021903046d61696e05022501057368696d7305022803026f7405021b0207706563696669630502270205716c69746505020d0204746f72650502080102763005022101057768696c650502220203696c6c050205030274680502140406090707070c070b0d0f0e090d07060b0a0b0907070a0c0d0e090a070c0a09070a08');
CREATE TABLE IF NOT EXISTS 'learnings_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
INSERT INTO learnings_fts_idx VALUES(1,X'',2);
INSERT INTO learnings_fts_idx VALUES(2,X'',2);
INSERT INTO learnings_fts_idx VALUES(3,X'',2);
INSERT INTO learnings_fts_idx VALUES(4,X'',2);
INSERT INTO learnings_fts_idx VALUES(5,X'',2);
CREATE TABLE IF NOT EXISTS 'learnings_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
INSERT INTO learnings_fts_docsize VALUES(1,X'2d01');
INSERT INTO learnings_fts_docsize VALUES(2,X'3401');
INSERT INTO learnings_fts_docsize VALUES(3,X'2701');
INSERT INTO learnings_fts_docsize VALUES(4,X'2a01');
INSERT INTO learnings_fts_docsize VALUES(5,X'2701');
CREATE TABLE IF NOT EXISTS 'learnings_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
INSERT INTO learnings_fts_config VALUES('version',4);
CREATE TABLE learning_tags (
  learning_id  TEXT NOT NULL REFERENCES learnings(id),
  tag          TEXT NOT NULL,
  PRIMARY KEY (learning_id, tag)
);
INSERT INTO sqlite_sequence VALUES('events',29);
INSERT INTO sqlite_sequence VALUES('dependencies',12);
CREATE VIEW task_readiness AS
SELECT
  t.id,
  t.status,
  COUNT(CASE
    WHEN d.kind IN ('blocks', 'feeds_into')
     AND upstream.status NOT IN ('done', 'done_partial')
    THEN 1
  END) AS unmet_deps,
  CASE
    WHEN t.status = 'pending'
     AND COUNT(CASE
         WHEN d.kind IN ('blocks','feeds_into')
          AND upstream.status NOT IN ('done','done_partial')
         THEN 1 END) = 0
    THEN 1 ELSE 0
  END AS promotable
FROM tasks t
LEFT JOIN dependencies d ON d.to_task = t.id
LEFT JOIN tasks upstream ON upstream.id = d.from_task
GROUP BY t.id;
CREATE INDEX idx_tasks_project_status ON tasks(project_id, status);
CREATE INDEX idx_tasks_parent ON tasks(parent_task_id);
CREATE INDEX idx_dependencies_from ON dependencies(from_task);
CREATE INDEX idx_dependencies_to ON dependencies(to_task);
CREATE INDEX idx_events_project_timestamp ON events(project_id, timestamp);
CREATE INDEX idx_task_tags_tag ON task_tags(tag);
CREATE INDEX idx_task_notes_task ON task_notes(task_id);
CREATE INDEX idx_task_files_task ON task_files(task_id);
CREATE INDEX idx_task_files_path ON task_files(path);
CREATE INDEX idx_learnings_project ON learnings(project_id);
CREATE INDEX idx_learnings_task ON learnings(task_id);
CREATE INDEX idx_learning_tags_tag ON learning_tags(tag);
PRAGMA writable_schema=OFF;
COMMIT;
