-- Chief OS PlanDB state snapshot — AUTHORITATIVE
-- Auto-generated by scripts/plandb-export.sh — do not hand-edit.
-- Source: /Users/santoshkumarradha/Documents/agentfield/code/labs/chief-os-w5-ui/.plandb.db
-- Generated: 2026-04-22T00:07:11Z
-- Restore: scripts/plandb-restore.sh (uses this file).

/* WARNING: Script requires that SQLITE_DBCONFIG_DEFENSIVE be disabled */
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE projects (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  description  TEXT,
  status       TEXT NOT NULL DEFAULT 'active',
  metadata     JSON,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO projects VALUES('p-7lhy','chief-ui-v0',NULL,'active',NULL,'2026-04-21 23:46:41','2026-04-21 23:46:41');
CREATE TABLE tasks (
  id                 TEXT PRIMARY KEY,
  project_id         TEXT NOT NULL REFERENCES projects(id),
  parent_task_id     TEXT REFERENCES tasks(id),
  is_composite       BOOLEAN NOT NULL DEFAULT FALSE,
  title              TEXT NOT NULL,
  description        TEXT,
  status             TEXT NOT NULL DEFAULT 'pending',
  kind               TEXT NOT NULL DEFAULT 'generic',
  priority           INTEGER NOT NULL DEFAULT 0,
  agent_id           TEXT,
  claimed_at         DATETIME,
  started_at         DATETIME,
  completed_at       DATETIME,
  result             JSON,
  error              TEXT,
  progress           INTEGER,
  progress_note      TEXT,
  max_retries        INTEGER NOT NULL DEFAULT 0,
  retry_count        INTEGER NOT NULL DEFAULT 0,
  retry_backoff      TEXT NOT NULL DEFAULT 'exponential',
  retry_delay_ms     INTEGER NOT NULL DEFAULT 1000,
  timeout_seconds    INTEGER,
  heartbeat_interval INTEGER NOT NULL DEFAULT 30,
  last_heartbeat     DATETIME,
  requires_approval  BOOLEAN NOT NULL DEFAULT FALSE,
  approval_status    TEXT,
  approved_by        TEXT,
  approval_comment   TEXT,
  pre_condition      TEXT,
  post_condition     TEXT,
  pre_hook           TEXT,
  post_hook          TEXT,
  metadata           JSON,
  created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tasks VALUES('t-inspect-specs','p-7lhy',NULL,0,'Inspect UI specs and repo shape','Read ADR-0011, docs/18-ui-standardization.md, docs/brand/visual-language.md sections 4-7, root Cargo.toml, and any existing package manifests under packages/chief-ui-ts or crates/chief-ui if present. Produce concrete implementation constraints: token values, package tooling, export shape, and verification commands. Acceptance: enough context gathered to implement without touching forbidden paths.','done','generic',0,'default','2026-04-21 23:47:15','2026-04-21 23:47:15','2026-04-21 23:48:21','"Inspected ADR-0011, docs/18-ui-standardization.md, visual language sections 4-7, root Cargo.toml, package/crate layout, and available tooling. Implementation will create new packages/chief-ui-ts and crates/chief-ui, plus add the Rust crate to root Cargo.toml only. Verification will use npm scripts backed by global tsc/node:test and cargo package checks."',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 23:47:15',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 23:46:48','2026-04-21 23:48:21');
INSERT INTO tasks VALUES('t-ts-package','p-7lhy',NULL,0,'Implement TypeScript package','Create or update packages/chief-ui-ts only. Add tokens.css, React primitive components matching the exact catalog, public index exports only Chief primitives, Tauri vibrancy helper, internal shadcn scaffold with MIT attribution, font bundling assets/attribution, README 30-line example, and focused unit/snapshot/type-guard tests. Acceptance: package build and tests pass locally, public entry does not export Radix/Shadcn internals.','done','generic',0,'default','2026-04-21 23:48:21','2026-04-21 23:48:21','2026-04-21 23:57:17','"Implemented TS primitive kit and verified with npm run typecheck and npm test. Known environment gap: Inter Tight font binary could not be bundled because it is not present locally and network DNS resolution for github.com is blocked; CSS and attribution are wired for assets/fonts/InterTight-Regular.ttf."',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 23:48:21',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 23:46:53','2026-04-21 23:57:17');
INSERT INTO tasks VALUES('t-rust-crate','p-7lhy',NULL,0,'Implement Rust companion','Create or update crates/chief-ui only. Mirror Chief UI prop types and token constants in Rust, including closed enums for source colors and badges, motion/token data, and serde-friendly structs where appropriate. Acceptance: crate builds and tests pass without modifying other Rust crates.','done','generic',0,'default','2026-04-21 23:57:17','2026-04-21 23:57:17','2026-04-21 23:59:32','"Implemented crates/chief-ui with token constants, motion presets, closed source/badge enums, serde prop mirrors, and contract tests. Ran rustfmt directly. Cargo test is deferred until the verify task updates root Cargo.toml workspace membership."',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 23:57:17',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 23:46:59','2026-04-21 23:59:32');
INSERT INTO tasks VALUES('t-verify','p-7lhy',NULL,0,'Register workspace and verify','Update root Cargo.toml to include crates/chief-ui, then run npm/package checks for packages/chief-ui-ts and cargo checks/tests for crates/chief-ui or the workspace member. Acceptance: all requested builds/tests pass or any environment blocker is recorded with exact command output.','done','generic',0,'default','2026-04-21 23:59:32','2026-04-21 23:59:32','2026-04-22 00:01:43','"Registered crates/chief-ui in root Cargo.toml. Verified TS with npm run build, npm run typecheck, npm test. Verified Rust with cargo fmt --check -p chief-ui, cargo test -p chief-ui --offline, and cargo check -p chief-ui --offline. Non-offline cargo failed because DNS for index.crates.io is blocked. Public TS root entry exports only requested primitives. Inter Tight font asset remains unavailable in this sandbox; Inter and JetBrains Mono are bundled."',NULL,NULL,NULL,0,0,'exponential',1000,NULL,30,'2026-04-21 23:59:32',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21 23:47:05','2026-04-22 00:01:43');
CREATE TABLE dependencies (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  from_task    TEXT NOT NULL REFERENCES tasks(id),
  to_task      TEXT NOT NULL REFERENCES tasks(id),
  kind         TEXT NOT NULL DEFAULT 'blocks',
  condition    TEXT NOT NULL DEFAULT 'all',
  metadata     JSON,
  UNIQUE(from_task, to_task)
);
INSERT INTO dependencies VALUES(1,'t-inspect-specs','t-ts-package','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(2,'t-inspect-specs','t-rust-crate','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(3,'t-ts-package','t-verify','feeds_into','all',NULL);
INSERT INTO dependencies VALUES(4,'t-rust-crate','t-verify','feeds_into','all',NULL);
CREATE TABLE artifacts (
  id           TEXT PRIMARY KEY,
  task_id      TEXT NOT NULL REFERENCES tasks(id),
  name         TEXT NOT NULL,
  kind         TEXT,
  content      TEXT,
  path         TEXT,
  size_bytes   INTEGER,
  mime_type    TEXT,
  metadata     JSON,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE events (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id      TEXT REFERENCES tasks(id),
  project_id   TEXT REFERENCES projects(id),
  agent_id     TEXT,
  event_type   TEXT NOT NULL,
  payload      JSON,
  timestamp    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO events VALUES(1,'t-inspect-specs','p-7lhy',NULL,'task_created','{"title":"Inspect UI specs and repo shape"}','2026-04-21 23:46:48');
INSERT INTO events VALUES(2,'t-ts-package','p-7lhy',NULL,'task_created','{"title":"Implement TypeScript package"}','2026-04-21 23:46:53');
INSERT INTO events VALUES(3,'t-rust-crate','p-7lhy',NULL,'task_created','{"title":"Implement Rust companion"}','2026-04-21 23:46:59');
INSERT INTO events VALUES(4,'t-verify','p-7lhy',NULL,'task_created','{"title":"Register workspace and verify"}','2026-04-21 23:47:05');
INSERT INTO events VALUES(5,'t-inspect-specs','p-7lhy','default','task_claimed',NULL,'2026-04-21 23:47:15');
INSERT INTO events VALUES(6,'t-inspect-specs','p-7lhy','default','task_started',NULL,'2026-04-21 23:47:15');
INSERT INTO events VALUES(7,'t-inspect-specs','p-7lhy','default','task_completed','{"has_result":true}','2026-04-21 23:48:21');
INSERT INTO events VALUES(8,'t-ts-package','p-7lhy','default','task_claimed',NULL,'2026-04-21 23:48:21');
INSERT INTO events VALUES(9,'t-ts-package','p-7lhy','default','task_started',NULL,'2026-04-21 23:48:21');
INSERT INTO events VALUES(10,'t-ts-package','p-7lhy','default','task_completed','{"has_result":true}','2026-04-21 23:57:17');
INSERT INTO events VALUES(11,'t-rust-crate','p-7lhy','default','task_claimed',NULL,'2026-04-21 23:57:17');
INSERT INTO events VALUES(12,'t-rust-crate','p-7lhy','default','task_started',NULL,'2026-04-21 23:57:17');
INSERT INTO events VALUES(13,'t-rust-crate','p-7lhy','default','task_completed','{"has_result":true}','2026-04-21 23:59:32');
INSERT INTO events VALUES(14,'t-verify','p-7lhy','default','task_claimed',NULL,'2026-04-21 23:59:32');
INSERT INTO events VALUES(15,'t-verify','p-7lhy','default','task_started',NULL,'2026-04-21 23:59:32');
INSERT INTO events VALUES(16,'t-verify','p-7lhy','default','task_completed','{"has_result":true}','2026-04-22 00:01:43');
CREATE TABLE task_tags (
  task_id  TEXT NOT NULL REFERENCES tasks(id),
  tag      TEXT NOT NULL,
  PRIMARY KEY (task_id, tag)
);
CREATE TABLE plandb_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
INSERT INTO plandb_meta VALUES('current_project','p-7lhy');
CREATE TABLE task_notes (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES tasks(id),
  agent_id TEXT,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE task_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id TEXT NOT NULL REFERENCES tasks(id),
  path TEXT NOT NULL,
  UNIQUE(task_id, path)
);
CREATE TABLE learnings (
  id           TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL REFERENCES projects(id),
  task_id      TEXT REFERENCES tasks(id),
  agent_id     TEXT,
  kind         TEXT NOT NULL DEFAULT 'discovery',
  content      TEXT NOT NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO learnings VALUES('c-i635','p-7lhy','t-inspect-specs','default','discovery','Spec inspection: chief-ui packages do not exist yet. Allowed edit scope is packages/chief-ui-ts/**, crates/chief-ui/**, and root Cargo.toml. Token values come from docs/18-ui-standardization.md and docs/brand/visual-language.md sections 4-7. No root JS package/lockfile or node_modules exist; global node/npm/tsc are available, vitest is not. TypeScript package should be self-contained for tsc/node:test verification, keep React as peer dependency, and avoid runtime imports in tests that require installed React.','2026-04-21 23:48:12');
INSERT INTO learnings VALUES('c-huqn','p-7lhy','t-ts-package','default','discovery','TypeScript package created under packages/chief-ui-ts with primitives, tokens.css, Tauri vibrancy helper, internal shadcn MIT attribution, README 30-line example, and node:test/type-guard/snapshot tests. npm typecheck and npm test pass using global tsc/node. Font status: Inter-Regular.ttf and JetBrainsMono-Regular.ttf were copied from local OFL fonts; Inter Tight was not found locally and direct GitHub download failed because DNS/network is blocked.','2026-04-21 23:57:12');
INSERT INTO learnings VALUES('c-s4bc','p-7lhy','t-rust-crate','default','discovery','Rust companion crate created under crates/chief-ui with tokens.rs constants, motion presets, closed enums, serde prop mirrors, and contract tests. cargo test cannot run until root Cargo.toml includes crates/chief-ui as a workspace member; that is the next verification task.','2026-04-21 23:59:27');
PRAGMA writable_schema=ON;
INSERT INTO sqlite_schema(type,name,tbl_name,rootpage,sql)VALUES('table','learnings_fts','learnings_fts',0,'CREATE VIRTUAL TABLE learnings_fts USING fts5(
  content,
  kind,
  content=''learnings'',
  content_rowid=''rowid''
)');
CREATE TABLE IF NOT EXISTS 'learnings_fts_data'(id INTEGER PRIMARY KEY, block BLOB);
INSERT INTO learnings_fts_data VALUES(1,X'03814903');
INSERT INTO learnings_fts_data VALUES(10,X'000000000103030003010101020101030101');
INSERT INTO learnings_fts_data VALUES(137438953473,X'000002860330313801021f01013401022a01013701022b0107616c6c6f77656401020b02026e640106160f2d0202726501023902017301024b02087661696c61626c6501023a03036f696401024f01026265010241020472616e640102250105636172676f0102180204686965660106040e0602036f6d6501021c03076e7461696e656401024302057261746573010213010a646570656e64656e637901024d02086973636f76657279010601010202016f0102070302637301041e0801046564697401020c0204786973740104092d0103666f720102440203726f6d01021d0106676c6f62616c0102350107696d706f72747301025102016e01025203087370656374696f6e010203040674616c6c656401025602017301040e3001026a7301022e01046b65657001024901086c616e677561676501022702076f636b66696c6501023001026d640104220802066f64756c657301023301026e6f01022c030264650106320612030174010408370202706d01023701026f7201023101077061636b61676501042f120801730104060b020365657201024c0105726561637401044a0f0305717569726501025502036f6f74010417180206756e74696d65010250010573636f706501020d0207656374696f6e7301022903026c660102420205686f756c640102400203706563010202020e74616e64617264697a6174696f6e010221010474657374010247050173010253020368617401025402046f6b656e01021a03026d6c0102190201730102120301630104380f020979706573637269707401023e010275690108050e060d010676616c75657301021b020b6572696669636174696f6e0102480205697375616c01022603047465737401023b010379657401020a040706060c0907060d0807090a0b080c0a0f0f0608090a08080b0c060d0b0707090d0c080b07090707070d07080b0a090b0a0c070a0813090608090706070e0a0b100a09');
INSERT INTO learnings_fts_data VALUES(274877906945,X'0000025c033033300202160103616e640208190b0f12020a74747269627574696f6e02021401076265636175736502024402066c6f636b65640202480105636869656602020702056f7069656402023402067265617465640202040202737302020d0106646972656374020240030773636f76657279020601010202026e7302024502076f776e6c6f616402024201076578616d706c6502021801066661696c656402024302036f6e7402022a0501730202380303756e6402023d0203726f6d020235010667697468756202024102056c6f62616c02022702047561726402021d010668656c7065720202100105696e74657202042c0f06036e616c020211020173020247010d6a6574627261696e736d6f6e6f02023001046c696e6502021702046f63616c02023606026c7902023e01036d697402021301076e6574776f726b02024602036f646502041a1103017402023c0202706d0204200501036f666c02023701077061636b61676502020308017302020603027373020225020972696d69746976657302020b0106726561646d65020215030567756c617202042d06010673686164636e02021202076e617073686f7402021e0205746174757302022b0105746175726902020e020365737402041b0b05017302021f02046967687402023a02056f6b656e7302020c0201730202090301630202280202746602042e06020379706502021c0505636865636b02022105067363726970740202020102756902020802046e646572020205020473696e67020226010876696272616e637902020f010377617302023b0203657265020233020369746802020a04070b0f0c0b0a0a0b070b0e070c0c0b080608080b0a090b0b080612090907080c090608080c06070e0b0b0b0c0a0a0906090a060608080a0b0709090d0808');
INSERT INTO learnings_fts_data VALUES(412316860417,X'0000018202306103022502026e64030215020173030224010663616e6e6f7403021a030372676f030418080204686965660304081c02056c6f73656403021002086f6d70616e696f6e03020303076e7374616e747303020d040574726163740302160204726174650302040601730304071c030565617465640302050109646973636f7665727903060101020105656e756d730302110108696e636c7564657303022002017303022901066d656d62657203022702066972726f727303021402056f74696f6e03020e01046e65787403022b01077072657365747303020f03026f700302130104726f6f7403021d02017303020c0202756e03021b030273740302020105736572646503021201047461736b03022d0203657374030219050173030217020368617403022803016503022a02056f6b656e7303020b03026d6c03021f010275690304091c02046e646572030206030374696c03021c010c766572696669636174696f6e03022c01047769746803020a02086f726b7370616365030226040607060b090a0a0d0c0a09070a100a0d060b0b0a090c07090607070a09080608060a070809081109');
CREATE TABLE IF NOT EXISTS 'learnings_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
INSERT INTO learnings_fts_idx VALUES(1,X'',2);
INSERT INTO learnings_fts_idx VALUES(2,X'',2);
INSERT INTO learnings_fts_idx VALUES(3,X'',2);
CREATE TABLE IF NOT EXISTS 'learnings_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
INSERT INTO learnings_fts_docsize VALUES(1,X'5601');
INSERT INTO learnings_fts_docsize VALUES(2,X'4701');
INSERT INTO learnings_fts_docsize VALUES(3,X'2c01');
CREATE TABLE IF NOT EXISTS 'learnings_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
INSERT INTO learnings_fts_config VALUES('version',4);
CREATE TABLE learning_tags (
  learning_id  TEXT NOT NULL REFERENCES learnings(id),
  tag          TEXT NOT NULL,
  PRIMARY KEY (learning_id, tag)
);
INSERT INTO sqlite_sequence VALUES('events',16);
INSERT INTO sqlite_sequence VALUES('dependencies',4);
CREATE VIEW task_readiness AS
SELECT
  t.id,
  t.status,
  COUNT(CASE
    WHEN d.kind IN ('blocks', 'feeds_into')
     AND upstream.status NOT IN ('done', 'done_partial')
    THEN 1
  END) AS unmet_deps,
  CASE
    WHEN t.status = 'pending'
     AND COUNT(CASE
         WHEN d.kind IN ('blocks','feeds_into')
          AND upstream.status NOT IN ('done','done_partial')
         THEN 1 END) = 0
    THEN 1 ELSE 0
  END AS promotable
FROM tasks t
LEFT JOIN dependencies d ON d.to_task = t.id
LEFT JOIN tasks upstream ON upstream.id = d.from_task
GROUP BY t.id;
CREATE INDEX idx_tasks_project_status ON tasks(project_id, status);
CREATE INDEX idx_tasks_parent ON tasks(parent_task_id);
CREATE INDEX idx_dependencies_from ON dependencies(from_task);
CREATE INDEX idx_dependencies_to ON dependencies(to_task);
CREATE INDEX idx_events_project_timestamp ON events(project_id, timestamp);
CREATE INDEX idx_task_tags_tag ON task_tags(tag);
CREATE INDEX idx_task_notes_task ON task_notes(task_id);
CREATE INDEX idx_task_files_task ON task_files(task_id);
CREATE INDEX idx_task_files_path ON task_files(path);
CREATE INDEX idx_learnings_project ON learnings(project_id);
CREATE INDEX idx_learnings_task ON learnings(task_id);
CREATE INDEX idx_learning_tags_tag ON learning_tags(tag);
PRAGMA writable_schema=OFF;
COMMIT;
